AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  stackName:
    Type: String
  frontendBucketName:
    Type: String
  lambdaFile:
    Type: String
  lambdaBucket:
    Type: String
  apiGatewayStageName:
    Type: String
    Default: api

Resources:

  # frontend

  cloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2
        PriceClass: PriceClass_100
        Origins:
         - Id: !Sub "ID-${frontendBucketName}"
           DomainName: !Sub "${frontendBucketName}.s3.eu-central-1.amazonaws.com"
           S3OriginConfig:
             OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${cloudfrontOriginIdentity}"
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          DefaultTTL: 600
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          TargetOriginId: !Sub "ID-${frontendBucketName}"
          ViewerProtocolPolicy: redirect-to-https

  cloudfrontOriginIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'foobar'

  s3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref frontendBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
            AllowedOrigins:
              - '*'
            ExposedHeaders:
              - Date
            MaxAge: 3600
    DeletionPolicy: Delete

  s3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref s3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser: !GetAtt cloudfrontOriginIdentity.S3CanonicalUserId
            Action: 's3:GetObject'
            Resource:  !Sub "arn:aws:s3:::${s3Bucket}/*"

  # backend
  lambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Effect: "Allow"
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${stackName}:*"
          PolicyName: "lambda"

  lambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: !Ref lambdaBucket
        S3Key: !Ref lambdaFile
      Environment:
        Variables:
          NODE_ENV: production
      FunctionName: !Sub "${stackName}-api"
      Handler: runtime.handler
      MemorySize: 128
      Role: !GetAtt lambdaRole.Arn
      Runtime: "nodejs14.x"
      Timeout: 5

  prerenderLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: !Ref lambdaBucket
        S3Key: !Ref lambdaFile
      Environment:
        Variables:
          NODE_ENV: production
      FunctionName: !Sub "${stackName}-prerender"
      Handler: prerender.handler
      MemorySize: 128
      Role: !GetAtt lambdaRole.Arn
      Runtime: "nodejs14.x"
      Timeout: 5

  lambdaLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/aws/${stackName}"
      RetentionInDays: 90

  apigw:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Ref stackName
      ProtocolType: HTTP

  apigwStage:
    Type: "AWS::ApiGatewayV2::Stage"
    Properties:
      ApiId: !Ref apigw
      StageName: !Ref apiGatewayStageName
      AutoDeploy: true
      DefaultRouteSettings:
        DetailedMetricsEnabled: true
        DataTraceEnabled: false
        ThrottlingBurstLimit: 10
        ThrottlingRateLimit: 10

  apigwInvokeApiLambda:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt lambdaFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${apigw}/*/*/*"

  apigwInvokePrerenderLambda:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt prerenderLambdaFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${apigw}/*/*/*"

  apigwIntegrationApi:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref apigw
      IntegrationMethod: POST
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub
        - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations"
        - lambdaArn: !GetAtt lambdaFunction.Arn
      PayloadFormatVersion: 2.0

  apigwIntegrationPrerender:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref apigw
      IntegrationMethod: POST
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub
        - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations"
        - lambdaArn: !GetAtt prerenderLambdaFunction.Arn
      PayloadFormatVersion: 2.0

  apigwRouteGet:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref apigw
      RouteKey: "GET /runtime/{req+}"
      Target: !Sub "integrations/${apigwIntegrationApi}"

  apigwPrerenderRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref apigw
      RouteKey: "GET /prerender"
      Target: !Sub "integrations/${apigwIntegrationPrerender}"

Outputs:
  apiGatewayInvokeURL:
    Value: !Sub "https://${apigw}.execute-api.${AWS::Region}.amazonaws.com/${apiGatewayStageName}"

  cloudfrontDistributionId:
    Value: !Ref cloudfrontDistribution

  cloudfrontDomainName:
    Value: !GetAtt cloudfrontDistribution.DomainName
