version: '3.8'

services:
  backend:
    image: ${BACKEND_IMAGE}
    restart: on-failure
    environment:
      MFE_FRONTEND_URL: "${MFE_FRONTEND_URL}"
    volumes:
      - '/tmp/current-weather:/tmp'
    ports:
      - '${MFE_BACKEND_PORT}:8080'

  frontend:
    image: ${FRONTEND_IMAGE}
    restart: on-failure
    environment:
      MFE_FRONTEND_URL: "${MFE_FRONTEND_URL}"
      MFE_BACKEND_URL: "${MFE_BACKEND_URL}"
    volumes:
      - './docker.nginx.frontend.conf:/etc/nginx/conf.d/default.conf:ro'
      - './docker.nginx.frontend.sh:/docker-entrypoint.d/30-set-backend-url.sh:ro'
    ports:
      - '${MFE_FRONTEND_PORT}:80'
